bazelbuild/bazelisk

.bazelci/config.yml
BUILD
WORKSPACE
bazelisk.go
bazelisk_test.sh
go.mod
go.sum

It has feature parity with the Python version and is tested against the
same test suite.

Add an implementation of Bazelisk in Go.

---

bazelisk.go

Incompatible flag list is fetched from GitHub labels (`migration-xx.yy`).

Add --strict flag to automatically add incompatible flags

---

README.md
bazelisk.py

Just a quick README fix that I happened to notice.

The bazel binaries are now put inside the user cache dir

---

README.md

This has been done (bazelbuild/homebrew-tap#40).

Remove Homebrew TODO

---

bazelisk.py

To address https://github.com/philwo/bazelisk/issues/43, download bazelisk into a tempfile and only move it to the cache directory after the download fully succeeds.
Open to suggestions for how to test this.

Use tempfile for bazel download in bazelisk.py

---

bazelisk.go
bazelisk.py

If the workspace has `tools/bazel` and it's executable, set `$BAZEL_REAL` and delegate to the user's wrapper script. The Python version of Bazelisk also makes a best-effort check to ensure that the wrapper isn't Bazelisk itself; since it's unlikely that the user has checked in a compiled Go binary, the Go version doesn't bother with this check.
Compared to #46, this version prevents `bazelisk.py` from delegating to itself. (Apologies to @hperl - I'm happy to hand this whole PR over, or split the Python and Go bits into separate PRs.)
Fixes #1 and #51.

Delegate to tools/bazel if possible

---

README.md
bazelisk.go

Fixes https://github.com/bazelbuild/bazelisk/issues/73

Run clean between incompatible flag checks

---

bazelisk.go

The script will print "TBD" if the breaking release hasn't been determined yet.
Fixes #104

Display correct Bazel release which flips a flag

---

README.md
bazelisk.go
bazelisk_test.sh

Bonus: Small efficiency improvement in bazelisk.go
Fixes #140

Add tests and documentation for .bazeliskrc

---

bazelisk.go
bazelisk.py
bazelisk_test.sh

Prepend directory containing relevant `bazel` binary to `PATH`

---

bazelisk.go

Fix a bug that PATH on Windows will sometimes get overwritten

---

bazelisk.py

Fix dispatch with no arguments in bazelisk.py

---

bazelisk_test.sh

rules_go update in #159 broke the postsubmit.

Hacky attempt at fixing test.

---

.bazelci/config.yml
BUILD
WORKSPACE
core/BUILD
go.mod
go.sum
httputil/BUILD
platforms/BUILD
repositories/BUILD
versions/BUILD

Bump rules_go, gazelle versions, upgrade go-version to v1.2.1, re-run gazelle.

Some random clean-ups

---

.github/dependabot.yml

add dependabot for keeping the dependencies up to date.

deps: add dependabot

---

httputil/fake.go
httputil/httputil.go

Several exported entities didn't have a godoc comment.

Fix Go style issues in package httputil

---

bazelisk.py

Allowing Bazelisk to download Bazel without JDK

---

bazelisk.py

Reading auth from netrc when BAZELISK_BASE_URL is set

---

bazelisk.py

Formatting bazelisk.py with [Black](https://black.readthedocs.io/en/stable/)

Formatting bazelisk.py

---

platforms/platforms.go
repositories/gcs.go

Fixes https://github.com/bazelbuild/bazel/issues/16061

Show error for unsupported arm64 platforms

---

WORKSPACE
go.mod
go.sum
httputil/BUILD
httputil/httputil.go

Let's standardize on the one that we're already using internally.

Use different .netrc Go lib

---

bazelisk_version_test.go
core/core.go
platforms/platforms.go
repositories/github.go

Fix spelling

---

core/core.go

Due to a bug Bazelisk never read any binaries from the cache, thus resulting in severe runtime penalties.

Stop downloading existing Bazel binaries

---

core/core.go

When the given good bazel commit is a version number, we should use the resolved commit hash to check if we should override it to the merge base commit.

Improve the overriding of good bazel commit

---

WORKSPACE

Should fix https://github.com/bazelbuild/bazelisk/issues/405

Update rules_go to 0.42.0

---

bazelisk_test.sh

See https://github.com/bazelbuild/bazelisk/pull/465#issuecomment-1805905082

Disable test_path_is_consistent_regardless_of_base_url

---

.gitignore
MODULE.bazel
go.mod

Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

chore(bazel): add MODULE.bazel files for bzlmod

---

build.sh

This is a follow-up to #563, to add the new packages to the release process.

Release Debian Packages

---

MODULE.bazel
bazelisk_test.sh

Hopefully fixes https://buildkite.com/bazel/bazelisk/builds/3107#0197acf8-6de8-4c73-9d61-e035f5e0f28f

Update go version in MODULE.bazel

---

MODULE.bazel

To fix:
- https://github.com/bazelbuild/bazelisk/issues/701
- https://github.com/bazelbuild/bazelisk/issues/698

Update bazel_lib in MODULE.bazel
