bazelbuild/bazelisk

bazelisk.py

This means that you can pipe output from bazelisk query and it will be parseable.

Print to stderr instead of stdout

---

bazelisk.py

Previously, it would not get the latest major/minor version if a
minor/patch version of a previous release was released chronologically
later.

Update resolve_latest_version to always get latest

---

bazelisk.py

This is very noise as it prints that on each invokation and we define the strict version in .bazelversion anyway.
Possibly it would make sense to keep this for the latest->version resolve? But even then if someone is unsure of the version they could just run `bazel version`

Do not print which bazel version is being used

---

README.md
bazelisk.py

This adds support for `rc` versions, like this:
```
$ USE_BAZEL_VERSION=0.20.0rc1 bazelisk build //src:bazel
Using Bazel 0.20.0rc1...
Downloading https://releases.bazel.build/0.20.0/rc1/bazel-0.20.0rc1-darwin-x86_64...
```

Add support for release candidate versions

---

bazelisk.py

This PR fixes https://github.com/philwo/bazelisk/issues/13.
As per the commit message, the changes introduced by this PR do the following:
```
- Correctly fetch Bazel releases ending with ".exe" rather than without
when downloading on Windows.
- Recognise "amd64" and "AMD64" machine architectures as aliases for
"x86_64" when downloading Bazel.
```

Fix bugs on Windows and 64-bit architectures

---

README.md
bazelisk.py

Bazelisk now accepts "latest-1" to refer to the previous Bazel release, "latest-2" for the one before that, etc.
The current release can still be addressed as "latest" (but "latest-0" is also allowed).

Support "latest-N" version strings.

---

README.md
bazelisk.go

This will try separately each incompatible flag and show a report. This
is useful for identifying issues in the current code base.

Add --migrate flag to bazelisk in Go

---

bazelisk.go

1. sort all incompatible flags
2. Use `---` to print the output of individual Bazel run as a collapsed group
3. Use `+++` to print the result as a expanded group
Related doc: https://buildkite.com/docs/pipelines/managing-log-output

Optimize the output of `bazelisk --migrate ...` for Buildkite

---

bazelisk.go

- Exit with error code 1 if the build fails
- Fix a bug in a print message
- Insert arguments before "--" if any (otherwise, put them at the end)
Fixes https://github.com/philwo/bazelisk/issues/34

Fix error code and argument order

---

bazelisk.go

Current format returns https://releases.bazel.build/0.24.0rc5/5/bazel-0.24.0rc5-darwin-x86_64 and instead
it should be https://releases.bazel.build/0.24.0/rc5/bazel-0.24.0rc5-darwin-x86_64.

Update release candidate version format.

---

bazelisk.go

Instead of hard-coding the limit, we could also make multiple requests,
one for each page (https://developer.github.com/v3/#pagination).
But we don't expect the number of flags to grow indefinitely, so a limit
should work.
Fixes https://github.com/philwo/bazelisk/issues/40

Get up to 100 flags (instead of 30).

---

README.md
bazelisk.go
bazelisk.py
bazelisk_test.sh

This commit modifies both Bazelisk implementations to support the
"last_downstream_green" version identifier, which refers to a Bazel
binary built at the most recent commit that passed the downstream
pipeline on CI (https://buildkite.com/bazel/bazel-at-head-plus-downstream).
Part of https://github.com/bazelbuild/continuous-integration/issues/583.
Note: We cannot merge this PR until the pipeline actually uploads its first green commit.

Support last_downstream_green Bazel binary.

---

bazelisk.py

The `JSONDecodeError` type doesn't exist in Python 2.x:
```
Python 2.7.16 (default, Mar  4 2019, 09:01:38)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> dir(json)
['JSONDecoder', 'JSONEncoder', '__all__', '__author__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', '_default_decoder', '_default_encoder', 'decoder', 'dump', 'dumps', 'encoder', 'load', 'loads', 'scanner']
>>> dir(json.decoder)
['BACKSLASH', 'DEFAULT_ENCODING', 'FLAGS', 'JSONArray', 'JSONDecoder', 'JSONObject', 'NaN', 'NegInf', 'PosInf', 'STRINGCHUNK', 'WHITESPACE', 'WHITESPACE_STR', '_CONSTANTS', '__all__', '__builtins__', '__doc__', '__file__', '__name__', …
```

Make JSON exception version-agnostic

---

bazelisk.go

On Windows Bazelisk previously only read `.bazelversion` if you are in the same directory.
@philwo

Fixed searching of workspace on Windows.

---

bazelisk.go

Changed path.Join -> filepath.Join as it concerns filesystem paths. See #56, https://golang.org/pkg/path/filepath/#pkg-constants .

GOOS-friendly joins.

---

BUILD
README.md
bazelisk.go
bazelisk_test.sh

This commit introduces the "last_rc" version marker that makes Bazelisk use the most recent Bazel release candidate. If there is no active candidate, Bazelisk uses the latest release instead.
Currently this features is only supported in the Go version of Bazelisk, but not in the Python version.

Support 'last_rc' in Bazelisk [Go-only]

---

BUILD
bazelisk.go
stamp.sh

The version information is detected from git tags, with a fallback
to the latest git commit.
Fixes #65

Print bazelisk version formation when running 'bazel version'

---

README.md
bazelisk.go

This adds support for BAZELISK_GITHUB_TOKEN which is a GitHub token used
for API requests when it is set. This fixes the issue of being on a
shared network and getting rate limited when using bazelisk.
Fixes https://github.com/bazelbuild/bazelisk/issues/18

Add support for GitHub auth token

---

README.md
bazelisk.go
bazelisk_test.sh
build.sh

Bazelisk will set this environment variable when executing Bazel (or
a wrapper found in <workspace_root>/tools/bazel). This prevents Bazelisk
from executing itself in an infinite loop, in case the wrapper is
Bazelisk or somehow executes Bazelisk.
If you're using a wrapper in <workspace_root>/tools/bazel that downloads
Bazelisk and delegates to it, please set the BAZELISK_SKIP_WRAPPER
environment variable to ensure that Bazelisk directly executes Bazel.

Fix #61: Do not execute tools/bazel when BAZELISK_SKIP_WRAPPER is set.

---

.gitignore

If you use 'go build' the binary is output at this path

Add binary to gitignore

---

bazelisk.go

Fix the download error if there is an empty `.bazelversion`.
It would be useful and more robust when users temporarily need the latest version of Bazel, but they don't need to remove `.bazelversion`.

Fix empty .bazelversion download error

---

README.md
bazelisk.go

Support for installing custom Bazel version

---

BUILD
WORKSPACE
bazelisk.go
go.mod
go.sum

Bazel versions (e.g. in USE_BAZEL_VERSION or .bazelversion) can now
refer to absolute paths on the filesystem. As an added convenience, a
tilde prefix is expanded to the user's home directory.
Example:
```sh
$ USE_BAZEL_VERSION="~/bin/bazel-1.0" bazelisk
```
This would tell Bazelisk to not download any binaries and instead
just directly use the Bazel binary in `$HOME/bin/bazel-1.0`.

Allow using local Bazel binaries.

---

bazelisk_test.sh

Fix Bazelisk failure in Bazel CI Downstream after we always pass --test_env=USE_BAZEL_VERSION for all tests.
Fixing https://github.com/bazelbuild/bazel/issues/10024

bazelisk_test.sh: Unset USE_BAZEL_VERSION in setup

---

bazelisk.py

The `os.path.join()` here was resulting in `~/foo/./tools/bazel` being compared to `~/foo/tools/bazel`, which should actually match, but didn't.

Fix path comparison between tools/bazel and bazelisk source

---

bazelisk.go

When finding workspace root, also check the existence of WORKSPACE.bazel
file. Bazel supports WOKRSPACE.bazel file from 1.2.
Related https://github.com/bazelbuild/bazel/pull/10175

Support WORKSPACE.bazel file

---

bazelisk.go

For each flag, Bazelisk now also prints the Bazel version where the flag is supposed to be flipped, and the URL of the corresponding GitHub issue.
Required by https://github.com/bazelbuild/continuous-integration/issues/869

Inc flags: Display Bazel release and GitHub Issue

---

bazelisk.py

Some tooling may want to call Bazel more than once per invocation still using Bazelisk. They can integrate with Bazelisk by calling main() but that would mean a potential performance hit for Bazelisk to check Bazel version and cached binary multiple times.
With this change, Python tooling can import `get_bazel_path()` and `execute_bazel()` from bazelisk.py and call them appropriately.

Split main() to get_bazel_path() and execute_bazel()

---

README.md
bazelisk.go
bazelisk_test.sh

this is usefull to have for local networks. As long as the provided
url follows github release page format. For example, if you use
an artifactory repository and point it to github.
How it works is one can set `BAZELISK_BASE_URL` as long as that url follows the same pattern as github release page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bazelbuild/bazelisk/107)

add support to providing custom url for downloading the binaries

---

.bazelrc
BUILD
WORKSPACE
bazelisk.js
build.sh
package.json
rules_nodejs.pr1591.patch
stamp.sh

Add an npm package output

---

package.json

Right now having to install bazelisk and then setup a symlink to it under e.g. `/usr/bin/bazel` is a bit annoying.
By adding this, a user can immediately start running `bazel` commands via bazelisk (as well as `bazelisk` commands) after doing:
```
npm i -g @bazel/bazelisk
```
This is the suggested way to use bazelisk in the readme, and for the nodejs users I struggle to see many scenarios where you wouldn't want this to happen.

Make bazelisk available as "bazel" when installing via NPM

---

BUILD
README.md
bazelisk.go
bazelisk_version_test.go

This fallback strategy is NOT executed when users specify a fork of Bazel. In this case the version resolution algorithm fails immediately.
Note: This change only affects the origin of Bazel's version history. For upstream Bazel all binaries are downloaded from GCS, which has already been the case before this change.
Fixes #87

Retrieve Bazel versions from GCS if GitHub is down

---

bazelisk.go

If `tools/bazel` is a directory, the `maybeDelegateToWrapper` function tries to execute it, which results in a permission denied error.
This commit prevents that by checking if `tools/bazel` is a directory and ignores it.

Also check if `tools/bazel` is a directory

---

bazelisk_test.sh

Fixes the "Could not find the bazelisk executable" error that occurred in some test runs.

Fix test failure when building in debug mode

---

BUILD
README.md
bazelisk.go
bazelisk_test.sh
bazelisk_version_test.go
core/BUILD
core/repositories.go
httputil/BUILD
httputil/httputil.go
platforms/BUILD
platforms/platforms.go
repositories/BUILD
repositories/gcs.go
repositories/github.go
versions/BUILD
versions/versions.go

This change introduces dedicated interfaces to handle how Bazel versions are retrieved and downloaded.
The new `core` package introduces interfaces that represent four kinds of repositories that store Bazel versions: `ReleaseRepo`, `CandidateRepo`, `ForkRepo` and `CommitRepo`. Implementations of these interfaces must provide a list of available Bazel versions, as well as a function to download a desired version (`CommitRepo` is the exception since it must only return two commit hashes, last_green and last_downstream_green).
Implementations of these interfaces must be passed to the new `core.Repositories` struct, which uses them to resolve given Bazel versions and to return an appropriate download function. As a result, the download logic in bazelisk.go was reduced substantially.
The old …

Refactor Bazel version retrieval & downloads

---

BUILD

Bazelisk at downstream is failing: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1673
There seems to be a problem collecting test results, so I ran it locally.
Got message:
```
$ bazel test //:go_version_test 
ERROR: /usr/local/google/home/ilist/src/bazelisk/BUILD:67:8: GoCompilePkg go_version_test.internal.a failed (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src bazelisk.go -src bazelisk_version_test.go -arc ... (remaining 21 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src bazelisk.go …
```

Fix dependencies for go_version_test

---

.bazelci/config.yml
BUILD
bazelisk_version_test.go
core/repositories.go
repositories/gcs.go

If `latest-n` was requested, Bazelisk previously only examined the most recent version to see whether it had a release (and not just candidates).
If there was no release, Bazelisk simply returned the second-to-last one without checking whether that version had a release, too.
Now Bazelisk checks the latest versions until it finds one with a release.
Fixes #170
Progress towards #171

GO: Return latest version from GCS that is a full release

---

bazelisk_version_test.go
core/repositories.go
repositories/gcs.go

Previously the `latest-n` version identifier could point at incorrect Bazel versions since unreleased versions (i.e. release candidates) were not always discarded from the version history.
Since checking the complete Bazel history (starting with 0.1.0) is costly, this change also adds the lastN parameter to core.ReleaseRepo.GetReleaseVersions(). As a result, the code only examines as few versions as possible.
Fixes #171

GO: Fix latest-n release history from GCS

---

bazelisk_version_test.go

The new GCS setup helper removes boilerplate code from tests and makes it more clear which releases and candidates actually exist.

Simplify GCS test setup via a helper

---

BUILD
bazelisk_test.go
runfiles/BUILD
runfiles/runfiles.go

This is a pure refactoring, which makes it easier for us to use Bazelisk internally.

Move runfiles logic into separate package

---

README.md
bazelisk.go

In most cases Bazel binaries are fetched from GCS now, with the exception of forks (still on Github).

Fix documentation about release servers

---

bazelisk_test.sh
core/core.go

Fix accidental variable shadowing that broke version resolution.

---

bazelisk_version_test.go
repositories/gcs.go

This commit fixes two related problems: when version equaled "last_rc", Bazelisk-Go did not discard release versions, and it returned the "release" suffix as part of the version label (which was invalid, of course).
Fixes #189

Discard releases when reading candidates

---

core/core.go

On case-insensitive filesystems, bazelisk can fail to find the workspace root if you have a directory named `workspace/`. This patch updates `findWorkspaceRoot` to ensure that a workspace root is only returned if the WORKSPACE / WORKSPACE.bazel file exists and is not a directory, and makes bazelisk consistent with bazel itself (see comments in the patch for a link)

Fix workspace root detection by ignoring directories

---

bazelisk.py

The environment variable `BAZELISK_BASE_URL` is supported in the Go version. I would like to use that in the Python version too.

Supporting BAZELISK_BASE_URL in Python version

---

README.md
bazelisk.go
bazelisk_version_test.go
core/repositories.go
repositories/github.go
versions/versions.go

The current implementation accepts hardcoded versions of the format "5.0.0-pre.20210317[.1]", or the "rolling" literal which refers to the most recent rolling release.
Rolling releases are downloaded from GitHub, but we want to add GCS support soon, too.

Support rolling releases

---

bazelisk_test.go
core/core.go
httputil/httputil.go
repositories/gcs.go
repositories/github.go

Previously Bazelisk only read the first page of API responses.
Tested locally.

Implement pagination support for GitHub repos

---

BUILD
WORKSPACE
build.sh

With these changes, Bazelisk binaries for darwin-arm64 will be built.
Additionally, we build a universal Mac binary that can be used on amd64
and arm64 Macs and runs natively on either.

Fix #219: Provide ARM releases (for Mac M1)

---

README.md

Also move install instructions to the top, where impatient users will expect those.

Add note about ensuring developers have Bazelisk rather than Bazel

---

README.md
core/core.go
httputil/httputil.go

Until now Bazelisk has been using the default Go user agent when sending HTTP requests. Going forward Bazelisk will set a custom user agent that defaults to "Bazelisk/$version". Users can overwrite this value by setting the `BAZELISK_USER_AGENT` environment value.

Make the HTTP user agent configurable

---

BUILD
WORKSPACE
bazelisk_version_test.go
httputil/BUILD
httputil/fake.go
httputil/httputil.go
httputil/httputil_test.go

Bazelisk now retries failing HTTP requests whose status code indicates that a retry makes sense (e.g. 429, 503).
It considers a variety of HTTP headers (such as Retry-After, X-RateLimit-Reset, Rate-Limit-Reset) in order to determine when to retry.
If no such header is present Bazelisk employs an exponential backoff retry strategy (with some randomness).
Fixes #254

Add HTTP retry mechanism

---

httputil/httputil.go

The old value was too low to actually allow four retries.

Increase httputil.MaxRequestDuration to 30s

---

README.md

https://golang.org/doc/go-get-install-deprecation - "Deprecation of 'go get' for installing executables" says that using `go get` for installing binaries is deprecated and will not be supported starting from go1.18. It would be good to get users to get used to the "new way" in advance.

suggest 'go install' instead of 'go get'

---

httputil/httputil.go
httputil/httputil_test.go

https://github.com/bazelbuild/bazelisk/pull/256 introduced an incompatible issue with Golang versions prior to 1.13:
```
github.com/bazelbuild/bazelisk/httputil/httputil.go:117:25: invalid operation: 1 << attempt (shift count type int, must be unsigned integer)
```
This PR fixes the issue by forcing the `attempt` variable as an unsigned integer.

Use unsigned integer for shift count type

---

README.md
bazelisk_version_test.go
core/repositories.go
versions/versions.go

This version format allows users to work with the most recent stable release from a particular LTS track.
Fixes https://github.com/bazelbuild/bazelisk/issues/277

Support floating release identifiers (e.g. "5.x")

---

bazelisk_version_test.go
versions/versions.go

I have some patches I maintain in a fork of Bazel and generate binaries with `-patch` suffixes followed by a number (e.g. `4.2.1-patch1`) and would like to start using Bazelisk to download those binaries. This mostly works already except that Bazelisk does not accept the `-patch` patch versions. The change is pretty small so thought I'd open a pull requests to learn whether or not this patching pattern was a good idea or if maybe there's a better way. I also understand not everyone may be doing this so am open to other ideas and approaches for using patched Bazel versions.

Add support for patch versions of Bazel (e.g. `1.2.3-patch4`)

---

.gitignore
README.md
WORKSPACE
go.mod
go.sum
httputil/BUILD
httputil/httputil.go
repositories/github.go

This PR adds support for using .netrc file for getting credentials for Basic HTTP authentication to download bazel from protected resource.
Same as https://github.com/bazelbuild/bazelisk/pull/269 but for Go code.
Fixes #291 
Fixes #269 
Tested with JFrog Artifactory.

Parse .netrc for HTTP Basic authentication credentials when BAZELISK_BASE_URL points to protected resource

---

bazelisk.py

In some areas with unstable or slow internet, the downloaded Bazel may be corrupted. We should verify the hash of the downloaded binary, delete the binary and prompt users to try again if it is corrupted. For backward compatibility for existing mirrors that don't have sha256 file, we will skip the verification if the ".sha256" file doesn't exist.

Verifying the hash of downloaded Bazel binary

---

README.md

Hey wonderful bazelisk folks!
First and foremost, thanks for the absurdly useful tool you've built here. We love it.
@digitalcoyote was good enough make the PATH behavior for the (Windows) choco package parallel with (macOS) brew. (See #311) So I figured I should write a quick PR documenting his nice Chocolatey package in the README. Hopefully that'll make install nice and easy for new Windows users!  
Thanks for reading!
Chris
(ex-Googler)
Fixes #311

Add Windows chocolatey support to README.md

---

bazelisk.go
bazelisk_version_test.go
repositories/gcs.go
repositories/github.go

Closes https://github.com/bazelbuild/bazelisk/issues/228
Has the benefit of avoiding github rate limits on github actions when using rolling releases

Fetch rolling releases from GCS

---

platforms/platforms.go
repositories/gcs.go
test.sh

When using macOS on M1 and downloading a commit or any keyword that resolves to a commit (e.g., `last_green`) `bazelisk` was downloading from the url: `https://storage.googleapis.com/bazel-builds/artifacts/macos/[commit]/bazel`.
This PR changes the url to be of the form: `https://storage.googleapis.com/bazel-builds/artifacts/macos_arm64/[commit]/bazel`.
Also, to get tests to now pass on M1, `test.sh` has been updated to insert the arch determined from `uname -m` for the versions that support `arm64`.
See: https://github.com/bazelbuild/continuous-integration/issues/1338

Download native macOS arm64 binary on M1

---

core/core.go

---
22c287a Stop forwarding SIGINT to child processes
Since we handle os.Interrupt but no longer forward it to child
processes, this commit also removes platform-specific handling for
Windows, preferring to use child.Process.Kill() in all cases.
Fixes #307.
<br/>

Stop forwarding SIGINT to child processes

---

README.md
core/core.go

This allows for smoother migrations from globally pinned Bazel to project-local pinned Bazel using Bazelisk.

Teach custom fallback version behavior

---

platforms/platforms.go

We stopped publishing binaries for Ubuntu 14.04 some time ago, and we don't upload Arm64 Linux binaries (yet).
Consequently, Bazelisk on Linux should always fetch the regular Ubuntu 18.04 binaries for now.
Fixes https://github.com/bazelbuild/bazel/issues/16061

Download correct Bazel binary on Linux

---

README.md
core/core.go

This makes testing incompatible flags more flexible, both on CI or on users' local machines.
Working towards https://github.com/bazelbuild/continuous-integration/issues/1410

Support BAZELISK_INCOMPATIBLE_FLAGS for explicitly setting incompatible flags to be tested

---

bazelisk_version_test.go
core/repositories.go
repositories/BUILD
repositories/gcs.go

Using a floating version such as "5.x" previously meant that Bazelisk would send O(LTS releases) requests to GCS, thus resulting in noticeable lag.
This commit changes the code so that floating versions exploit a "stop early" optimization similar to the "last N" use case, thus resulting in significantly fewer GCS requests (from 106 down to two).
Fixes https://github.com/bazelbuild/bazelisk/issues/339

Fix performance issue for floating version values

---

core/core.go

This entry point is useful for consumers that need to set different arguments
depending on the Bazel version, e.g. if an option only exists in a recent
version.

Add a new RunBazeliskWithArgsFunc entry point.

---

platforms/platforms.go

As a result, Bazelisk should work on Ubuntu 14.04 and 16.04 again. Moreover, CentOS 7 is the most likely candidate for publishing arm64 Bazel binaries in the future.

Use Linux binaries built on CentOS 7

---

core/core.go

If startup options are missing, bazel shutdown/clean commands may end up shutdown the wrong server and clean up wrong caches if flags like --output_user_root is set.
This is needed for fixing Windows permission denied error found at https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1246#01831fc5-a439-4894-9418-0c4d7591fcfd

Pass startup options to bazel shutdown and bazel clean --expunge

---

bazelisk.py

Since the recommended replacement, `packaging.version`, is not in the standard library, this commit instead just implements a simple version number comparison without any additional dependencies.

Eliminate use of deprecated `distutils.version` module

---

core/core.go

If the `tools/bazel` wrapper is executable by the user, but not everyone the current behavior is that `bazelisk` assumes it's not executable and silently pretends that the wrapper script doesn't exist, which was very confusing to me.
After this change, someone could run into the case where `bazelisk` thinks the user can execute the wrapper, but doesn't actually have permission. If that does happen, the error `could not run Bazel: could not start Bazel: fork/exec /repo/tools/bazel: permission denied` makes it pretty clear what's wrong.
This now matches how the Go standard library checks if a file is executable. https://cs.opensource.google/go/go/+/refs/tags/go1.19:src/os/exec/lp_unix.go;l=26

Allow any execute bits to count as executable

---

README.md
bazelisk_test.sh
core/core.go

This change introduces support for locating multiple `.bazeliskrc` files, namely, in the workspace root and in the user home (`~/`) directory. Configuration in the former takes precedence over the latter. Semantically, this operates similarly to `.bazelrc`.
This change is backwards-compatible and does not introduce any new behaviors when there is only a single `.bazeliskrc` in the workspace.
The motivation is that I have some configuration (namely, `BAZELISK_BASE_URL`) that I'd like to set globally rather than versioning a `.bazeliskrc` into every Bazel project.
Concretely, here I have:
* Split out `GetEnvOrConfig` into multiple subroutines for locating the relevant RC files, parsing them individually, and loading them into the global configuration map, respecting precedence.
* …

Support user `.bazeliskrc` in addition to workspace root `.bazeliskrc`

---

core/core.go

This is just a nit but when I was reading this code yesterday this extra unused param threw me off for a sec

Removed unused param in core/core.go downloadBazel function

---

BUILD
WORKSPACE
go.mod
go.sum

Certain vulnerability scanners will flag bazelisk for being built with an outdated golang toolchain. To remediate this, update to the latest version of the go toolchain (1.19.3). Upgrade to the latest major version since 1.16 is EOL.
Also upgrades `rules_go` to `0.36.0` and `bazel_gazelle` to `0.28.0`. At the same time, removes the workaround to get output binaries placed into the appropriate directory since it's no longer necessary.

Bump go, rules_go, and bazel_gazelle

---

repositories/github.go

I tested this locally with a `.bazeliskrc` file with the following contents:
```
USE_BAZEL_VERSION=aspect-cli/latest
```
This will get the latest release from https://github.com/aspect-cli/bazel/releases.

fix: don't pass auth token in getFilteredVersions with BAZELISK_GITHUB_TOKEN is unset

---

core/core.go

`dirForURL` results in a "file name too long" error when using a path to a Bazel binary that is deeply nested in the FS as the bazel "version". This can happen in bazel integration tests that are using a static bazel binary, invoked via bazelisk.
Example failure: https://app.buildbuddy.io/invocation/11a56209-bdd7-412a-9a62-bda96f798117?target=%2F%2Fcli%2Ftest%2Fintegration%2Fcli%3Acli_test
`failed to run bazelisk: cound not link local Bazel: could not create directory /Users/administrator/buildbuddy.noindex/remote_build/11f02b5f-336d-4ce7-a01f-8b79df00fde9/output-base/sandbox/darwin-sandbox/2/execroot/buildbuddy/_tmp/e5ca0d86ab06654b9dcb40c80ba5e589/buildbuddy-test-1985373647/Library/Caches/bazelisk/local/-Users-administrator-buildbuddy-noindex-remote-build-11f02b5f-336d-4ce7-a01f-8b79df00 …

Fix 'file name too long' errors on darwin

---

core/BUILD
core/core.go
core/core_test.go

closes https://github.com/bazelbuild/bazelisk/issues/416

Add support for `tools/bazel.ps1` and `tools/bazel.bat` on Windows

---

bazelisk.py

Linux reports arm64 as aarch64. Correct for this so that Bazel can be fetched when on arm64/aarch64.

Support aarch64 in `bazelisk.py`.

---

README.md
bazelisk_test.sh
core/core.go

The new BAZELISK_VERIFY_SHA256 variable can be set to the expected SHA256 hash of the downloaded Bazel binary.  If set, then the binary is required to match the hash before it is used.
This is important for cases where provenance of the artifact cannot be asserted purely via the HTTPS trust chain (such as what happens in a mutable artifact repository with lax access controls).

Implement support for BAZELISK_VERIFY_SHA256

---

README.md
core/core.go

- Use --bisect=<BASE>..<HEAD> to specify the bisecting range, Bazelisk
uses the GitHub API to get the list of commits to bisect. You may need
to set `BAZELISK_GITHUB_TOKEN` to get around GitHub rate limit.
- BAZELISK_SHUTDOWN, BAZELISK_CLEAN can be used to run `bazel shutdown`
or `bazel clean --expunge` between builds.

Support bisecting Bazel to find which Bazel change breaks your build

---

core/core.go

We accidentally pushed [merge commits](https://github.com/bazelbuild/bazel/commits?author=Pavank1992) to master (during merging third party changes), this may break bisect since the publish Bazel binaries pipeline doesn't build at merge commits, therefore we skip those merge commits for bisecting.

--bisect: ignore merge commit

---

repositories/gcs.go

Addressing: https://github.com/bazelbuild/continuous-integration/issues/1627

Retry fetching Bazel versions from GCS URL

---

README.md
bazelisk_test.sh
core/BUILD
core/core.go
core/repositories.go
core/repositories_test.go
httputil/BUILD
platforms/BUILD
platforms/platforms.go

This new configuration setting provides a format-like string to compute the URL from which to fetch Bazel.  Takes precedence over BAZELISK_BASE_URL as this is a more general concept.
Fixes #423.

Implement support for BAZELISK_FORMAT_URL

---

bazelisk.py

> Bazel also supports WORKSPACE.bazel file as an alias of WORKSPACE file. If both files exist, WORKSPACE.bazel is used.
-- https://bazel.build/concepts/build-ref#workspace
The Go version already has this:
https://github.com/bazelbuild/bazelisk/blob/v1.16.0/core/core.go#L301

bazelisk.py notices WORKSPACE.bazel as a workspace_root

---

platforms/BUILD

Duplicated `go_tests` can result in compilation actions failing due to https://github.com/bazelbuild/rules_go/issues/3558.

Remove duplicated test

---

bazelisk_test.sh
core/core.go

Before this change, changing which mirror you were downloading from would change the $PATH environment variable bazel is run with, even though the bazel binaries being pointed to are identical. This can cause repository rules to invalidate and re-run.
Instead, store downloaded bazels in directories keyed off of the sha256 of the bazel binary itself, and track the metadata of a mirror+version -> sha256.
This avoid spurious rebuilds when only changing the URL bazelisk would use to download bazel.

Use consistent paths to bazel binaries

---

bazelisk.go
config/BUILD
config/config.go
core/BUILD
core/core.go
core/core_test.go
core/repositories.go
core/repositories_test.go
ws/BUILD
ws/ws.go

My goal here is to be able to pass my own config implementation when calling RunBazelisk from code without setting environment variables, because they cause repository rule cache invalidations.
As a side-effect, it helps towards the TODO in core.go to split functionality into packages.

Extract config fetching into its own package

---

WORKSPACE
httputil/BUILD

This enables other projects to depend on bazelisk using a gazelle
generated go_repository for com_github_bgentry_go_netrc, instead of
having to use the archive strip_prefix go_repository that Bazelisk
handcrafted.

go_netrc: switch back to gazelle style import

---

go.mod
go.sum

In theory bazelisk should not depend on rules_go, and indeed after a `go mod tidy`, `rules_go` went away. 
I searched around and didn't find too much context why rules_go was added.

Remove rules_go as deps

---

BUILD

My guess is this was broken by https://github.com/bazelbuild/bazelisk/pull/348
See docs: https://github.com/bazelbuild/rules_nodejs/blob/5.5.3/docs/stamping.md#substitutions-attribute

fix(npm): replace version placeholder with stamp value

---

bazelisk.py
ws/ws.go

As of Bazel 6.3.0, `MODULE.bazel` and `REPO.bazel` are also considered workspace boundaries. Bazelisk now searches for these in the same order Bazel does.
Fixes #502

Support `MODULE.bazel` and `REPO.bazel`

---

core/core.go

At the moment, `func getBazelVersion()` is scoped to the `core.go` package. I have made a small change to make this function public, so it can be called from other packages.

Make getBazelVersion func public

---

httputil/httputil_test.go

The lower bound has an off-by-one error:
2^0 + 2^1 + ... + 2^(n-1) sums up to 2^n-1.
Verified with:
go test -count=1000 -run TestShouldUseExponentialBackoffIfNoRetryHeader ./httputil -v

Fix TestShouldUseExponentialBackoffIfNoRetryHeader bounds

---

bazelisk_test.sh
core/core.go
core/repositories.go
platforms/BUILD
platforms/platforms.go
repositories/gcs.go
repositories/github.go

Inspired by #315 but implemented from scratch.
Fixes #430.
See individual commits in the PR for easier review.

Add support for BAZELISK_NOJDK to Go Bazelisk

---

core/core.go

This can be useful when invoking bazelisk programatically.

Allow specifying where stdout should get written

---

bazelisk.py

Split lines of .bazelversion and return first nonempty in bazelisk.py to support multiline .bazelversion in tensorflow.

Split lines of .bazelversion and return first nonempty.

---

core/core.go

In some projects the tools/bazel path isn't practical. This allows users to override this path with the BAZELISK_WRAPPER_DIRECTORY env var / .bazeliskrc config option. This allows overriding the root
directory that the `bazel` wrapper executable should be found in. This was chosen over the file itself
in order to continue supporting recursive `bazel` invocations.

Allow overriding tools/bazel path with BAZELISK_WRAPPER_DIRECTORY

---

core/core.go

Addressing a `TODO` comment to remove the backport of `strings.Cut`. It's no longer needed.

Go Bazelisk: `core.go` - removed backport of `strings.Cut` and use it instead

---

core/core.go

This is a proposal to add support for env expansion as `os.MkdirAll` will treat shell variables and `~` as literals.
Fixes https://github.com/bazelbuild/bazelisk/issues/586

`.bazeliskrc`: Add Support for Env Var and Tilde Expansion

---

BUILD
config/BUILD
core/BUILD
httputil/BUILD
httputil/progress/BUILD
platforms/BUILD
repositories/BUILD
versions/BUILD
ws/BUILD

Apparently gazelle no longer needs these specific names, and they make importing code into our internal repository much harder.

Remove go_default_library & go_default_test

---

MODULE.bazel
README.md
go.mod

As mentioned in the [Go Security Policy](https://go.dev/doc/security/#security-policysecuritypolicy), the [Release Policy](https://go.dev/doc/devel/release#policy) states:
> Each major Go release is supported until there are two newer major releases.
Therefore, Go `1.20` is End of Life and must be updated. This has security implications as reported by https://github.com/bazelbuild/bazelisk/issues/583
This PR upgrades Go to `1.22.5`, which currently is the latest release.
Fixes https://github.com/bazelbuild/bazelisk/issues/583
// cc: @creste

Upgrade: Go SDK to 1.22.5

---

BUILD
MODULE.bazel
build.sh
config/BUILD
core/BUILD
httputil/BUILD
httputil/progress/BUILD
platforms/BUILD
repositories/BUILD
versions/BUILD
ws/BUILD
ws/ws.go

Gazelle targets haven't been updated in a while. Took this opportunity to re-generate them.
Also, the `BUILD` file had many `go_binary` directives even though there are just two flavors: a stripped binary and another with all the symbols. Refactored to dinamically generate those based on the `os`, `arch` we should have for each flavor.
Added `windows-arm64`, tested in a workstation on Azure. Find evidence below.
> [!WARNING]  
> **bazelisk.js**: The NodeJS version installed in the machine must be ARM, otherwise `os.arch()` returns `x64` and it will use the `windows_amd64` binary.
Installed from: `npm i -g @bazel/bazelisk --registry=https://albertocavalcante.jfrog.io/artifactory/api/npm/bazel-npm-local`
Tested on a Windows ARM4 machine.
Context: …

Add Windows ARM64 and Refactored Targets

---

platforms/platforms.go

Depends on https://github.com/bazelbuild/continuous-integration/pull/2022
Fixes https://github.com/bazelbuild/bazelisk/issues/317
Bazel commits after https://github.com/bazelbuild/bazel/commit/5aaffc3aad61b003be3996af17641afedee9a2ec will be supported for Linux arm64.
We've been publishing under both "linux" and "centos7" for x64 binaries for a long time, so it should be fine to switch the name.

Fetch bazel binaries for commits on linux arm64

---

.bazelci/config.yml
MODULE.bazel
bazelisk_test.sh

Addressing https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4122#0191e992-fc74-4833-9d8d-21f46380f039
- Upgraded platforms we test for Bazelisk
- Fixed bazelisk_test.sh with WORKSPACE disabled.

Fix breakage with Bazel@HEAD

---

bazelisk_test.sh

sourceforge no longer hosts Bazel 6.2, so I had to use a newer version instead.

Fix & re-enable test_path_is_consistent_regardless_of_base_url

---

README.md
core/core.go

This can be useful for scripts that want to know if they are running under Bazelisk and can also be used to run specific Bazel versions from within a Bazel run, e.g. to generate version-specific test data.

Set `BAZELISK` var to `bazelisk` executable path

---

README.md
bazelisk.py
bazelisk_test.sh
core/repositories.go
repositories/gcs.go
test.sh
versions/versions.go

- Fetch last green commit from `https://storage.googleapis.com/bazel-builds/last_green_commit/github.com/bazelbuild/bazel.git/publish-bazel-binaries` which is generated by the trusted Bazel CI org.
- Validate the format of the commit hash fetched
- Removed support for `last_downstream_green`. The [downstream pipeline](https://buildkite.com/bazel/bazel-at-head-plus-downstream) hasn't been green for more than a year, there is not much point of using this commit for fetching Bazel binary.

Improve last green commit support

---

BUILD

build.sh builds //:npm_package.publish, which recently disappeared due to a combination of https://github.com/aspect-build/rules_js/pull/1683 and https://github.com/bazelbuild/bazelisk/pull/610.

Restore npm publish target

---

core/core.go

When two instances of Bazelisk are running concurrently and downloading Bazel, the current code admits a race. This patch fixes the issue by using randomly named files for temporary paths.
For example:
```
{"error":"could not download Bazel: failed to download bazel: failed to move /root/.bazel_binaries/stripe-bazel/downloads/sha256/09bac5c11165a6ab0b7a90d6937c8bc3fcdcda662ffe0590e87ac2ae0e5e8978/bin/bazel.tmp to /root/.bazel_binaries/stripe-bazel/downloads/sha256/09bac5c11165a6ab0b7a90d6937c8bc3fcdcda662ffe0590e87ac2ae0e5e8978/bin/bazel: rename /root/.bazel_binaries/stripe-bazel/downloads/sha256/09bac5c11165a6ab0b7a90d6937c8bc3fcdcda662ffe0590e87ac2ae0e5e8978/bin/bazel.tmp /root/.bazel_binaries/stripe-bazel/downloads/sha256/09bac5c11165a6ab0b7a90d6937c8bc3fcdcda662ffe0590e87ac2ae0e5e8978/ …
```

Fix races on temporary file copies

---

httputil/httputil.go

Hopefully fixes https://github.com/bazelbuild/bazelisk/issues/626

Close response body before retry

---

deb/BUILD

Without ca-certificates, we cannot fetch bazel from https.  (Closes: #622.)
We also conflict with bazel-bootstrap due to /usr/bin/bazel.

Fix some debian metadata

---

httputil/httputil.go
httputil/httputil_test.go

* add attempt count to the timeout error message so it's clear the timeout is due to the total time accumulated during retries.
* add lastFailure to the timeout error message so we can get a clear reason for the retries (or, at the very least, the last retry). Otherwise, the error message obscures the real reason(s) for the retries and potentially misleads users into thinking that the errors could be e.g. network related (more typical of a timeout) rather than other types of errors (e.g. "tls: failed to verify certificate", etc.)

feat: improve httputil error messages

---

bazelisk.go
bazelisk_version_test.go
core/repositories.go
repositories/gcs.go
versions/versions.go

This commit merges ReleaseRepo with CandidateRepo into a single type called LTSRepo.
1. The new behavior more closely resembles reality.
2. It will be much easier to implement https://github.com/bazelbuild/bazelisk/issues/630.
Progress towards https://github.com/bazelbuild/bazelisk/issues/630.

Refactor repositories API

---

README.md
bazelisk_version_test.go
core/repositories.go
repositories/gcs.go
versions/versions.go

Unlike the floating version identifier "N.x", "N.*" can also return release candidates.
Fixes https://github.com/bazelbuild/bazelisk/issues/630

Implement wildcard version identifier "N.*"

---

repositories/gcs.go

Follow-up to https://github.com/bazelbuild/bazelisk/pull/636.

Improve error message for missing LTS binaries

---

core/core.go

This would resolve branch name like `release-8.0.0rc2` to an actual commit hash, which is then a valid Bazel version for Bazelisk. 
This avoids error like:
```
--- Getting the list of commits between release-8.0.0rc2 and e18aad1be363fe40bad2cc67462a6389f381096b
Found 54 commits between (release-8.0.0rc2, e18aad1be363fe40bad2cc67462a6389f381096b]
--- Verifying if the given good Bazel commit (release-8.0.0rc2) is actually good
2024/11/18 12:58:03 could not run Bazel: could not download Bazel: could not resolve the version 'release-8.0.0rc2' to an actual version number: Invalid version 'release-8.0.0rc2'
```

bisect: always override oldCommit to the merge base commit

---

bazelisk_version_test.go
core/core.go
core/repositories.go
httputil/fake.go
platforms/platforms.go
repositories/gcs.go
versions/versions.go

The refactoring in https://github.com/bazelbuild/bazelisk/pull/631 introduced a severe performance regression: With latest and last_rc the code traversed *all* GCS buckets for *every* existing Bazel version. Since we send one HTTP request per bucket, this behavior led to a significant increase in HTTP requests ( >140 instead of 2-3 requests).
This commit restores the previous, correct behavior: Traversal will be stopped as soon as a matching version has been found.
Moreover, this commit adds a test to prevent similar regressions in the future.
Fixes https://github.com/bazelbuild/bazelisk/issues/640
Drive-by fix: Replaced \"%s\" with %q.

Avoid unnecessary HTTP requests for latest/last_rc

---

README.md
bazelisk.py
bazelisk_test.sh

This allows for suggesting (but not requiring) a bazel version using the bazeliskrc dotfile.

Teach bazelisk.py about .bazeliskrc

---

core/core.go

Every signal specially recognized by Bazel that doesn't cause an immediate exit shouldn't cause Bazelisk to exit either, as this risks orphaning the Bazel process and making it uncontrollable by the terminal. (You can see this in action by sending a Ctrl-\ to Bazelisk, which causes it to immediately exit and makes it impossible to abort the still running Bazel invocation with Ctrl-C.)
Note that forwarding is not necessary for a signal delivered by the terminal (i.e. through Ctrl-C or Ctrl-\\) because the terminal already delivers it to the entire process group. For manually delivered signals, users should arguably know what they're doing, so let's not go out of our way to forward them.
This also disables the printing of a Go stack dump upon SIGQUIT, which is unhelpful: users tend to …

Improve signal handling.

---

core/core.go

`bazelisk` can be thought of as two separate pieces. The first of these is a mechanism for locating a particular `bazel` version, possibly downloading it from the Web, or using a local install. The second piece is the additional functionality for flag flipping and finding out where problems have occurred within commits to the project.
This PR extracts the location of the `bazel` binary into its own method which can be used by other tooling that also needs to locate the binary.

Extract a method for locating Bazel

---

core/core.go

When invoking Bazelisk with the `version` command, the output should always start with the Bazelisk version followed by the output of `bazel version`. However, previously this was not the case when startup flags were set, e.g. when calling `bazelisk --nosystem_rc version`.

Print Bazelisk version when startup flags are set.

---

BUILD
MODULE.bazel
config/BUILD
core/BUILD
httputil/BUILD
httputil/progress/BUILD
platforms/BUILD
repositories/BUILD
versions/BUILD
ws/BUILD

When bazelisk is brought in as a Go dependency via gazelle's `go_deps` extension, it uses the repo mapping of the `gazelle` module to resolve loads. Since `gazelle` uses the legacy apparent names `bazel_gazelle` and `io_bazel_rules_go` for the `gazelle` and `rules_go` modules, the same is required for any Bazel module that is also a Go module (until gazelle gains the ability to fix load labels). 
This regressed in 4448ad1b1c77764b75a0e9a3d9605a7446f769d6.

Use legacy apparent names for rules_go and gazelle

---

bazelisk_test.sh

Addressing
```
2025/01/27 04:07:28 Downloading https://downloads.sourceforge.net/project/bazel.mirror/7.3.1/bazel-7.3.1-windows-x86_64.exe...
2025/01/27 04:07:28 could not download Bazel: failed to download bazel: failed to download bazel: HTTP GET https://downloads.sourceforge.net/project/bazel.mirror/7.3.1/bazel-7.3.1-windows-x86_64.exe failed with error 404
```

Fix bazelisk_test.sh

---

core/core.go

Signal handlers are process-wide global state and can affect the behavior of programs that use Bazelisk as a library.
Work towards https://github.com/buildbuddy-io/buildbuddy/issues/8326#issuecomment-2652249361

Reset signal handling after Bazel terminates

---

core/core.go

See comments in https://github.com/buildbuddy-io/buildbuddy/issues/8326 - `signal.Ignore()` is "permanent" so `Reset()` has no effect.

Ignore signals using notify/stop instead of ignore/reset

---

core/repositories.go

Both present the same kind of security risk. I don't see a strong reason to introduce a separate field instead of renaming and reusing the existing one.

Add the ability to forbid a format URL in addition to a base URL.

---

defs.bzl

This was unintentionally changed in #655.

Do not strip debugging symbols from Windows binaries.

---

README.md

Bazelisk can be installed via Scoop or WinGet, too.

Add how to install Bazelisk via Scoop or WinGet

---

BUILD
MODULE.bazel
deb/BUILD
defs.bzl

Run `buildifier --lint=fix  -r -v .`. This adds loads for the rules that were removed from Bazel 8. By Bazel 9 automatic loads will be disabled and all loads will need to be explicitly present.
Add dependency to `rules_shell` to `MODULE.bazel`.
See: https://github.com/bazelbuild/bazel/issues/25755

Run buildifier to add loads

---

go.mod

bump go version to 1.23.0 to fix
```
go: updates to go.mod needed; to update it:
go mod tidy
```
relates to https://github.com/Homebrew/homebrew-core/pull/219110

fix: bump go version to 1.23.0

---

core/core.go

Otherwise pressing Ctrl+C interrupts each individual Bazel command, but the bisection process itself continues.

Allow `--bisect` to be interrupted

---

README.md
core/core.go
core/core_test.go
platforms/platforms.go

This command prints shell completion scripts for the active Bazel version. The completion scripts are downloaded on-demand and cached to Bazelisk CAS cache. This is to support generating completion scripts for older Bazel versions.
Closes https://github.com/bazelbuild/bazelisk/issues/29

Add `bazelisk completion bash/fish` command

---

core/core.go
core/core_test.go

An equal sign '=' is a valid path character, but currently causes the `prependDirToPathList` function to ignore the existing PATH.
Fixes #719

handle PATH with '=' correctly

---

MODULE.bazel

Should fix https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4962#019974c3-8efc-4852-8f2d-04dc4f87a524

Bump rules_shell from 0.4.1 to 0.6.1
